@startuml 
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

package "FrontEnd" #DDDDDD {
  
  class Modelo_LDA_Final{

  }
    
  class Recomendacion{

  }


  class Docente {
    - int id_Docente
    String nombre
    

  }

  class Intereces {

  }

  class Expertiz {

  }

  class Custom_search {

  }
  

  
  

  class Documento {
  .. int ..
  - id_doc
  + year
  + Pages
  .. Strings ..
  + document_title
  - text
  .. Method ..
  + get_topic_vector()
  ~ void pre_procesar()

  }


}
  

package BackEnd #DDDDDD{
  class Pre_procesar
  
  class train_LDA

  class LDA_Model
  
  
}


package Database <<Database>> {

  
}



Database -- Pre_procesar



Database -- Documento

Intereces -- Docente 
Expertiz -- Docente 
Custom_search -- Docente
Recomendacion -- Custom_search
Recomendacion -- Expertiz
Recomendacion -- Intereces
Recomendacion -- Documento

Modelo_LDA_Final -- Recomendacion


Database -- Modelo_LDA_Final


Pre_procesar -- train_LDA
train_LDA -- LDA_Model

LDA_Model - Database

@enduml






Recomendacion - Documento
Recomendacion - Intereces
Recomendacion - Expertiz
Recomendacion - Custom_search

Database - Documento
Documento  	|o-- Docente : tiene
Recomendacion <- LDA_Model_Final

Intereces   	|o-- Docente : tiene
Expertiz   	}o-- Docente : tiene
Recomendacion - Documento
Recomendacion - Docente


note left: this class is a secretClass

<> diamond
() circle
abstract abstract 
annotation annotation      

class class
entity entity
enum enum
interface interface